blog/urls.py
from django.urls import path
from . import views
app_name='blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date=models.DateField()

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)


def __str__(self):
    return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
# Create your views here.
def all_blogs(request):
    blogs = Blog.objects.all().order_by('-date')[:5]
    return render(request,'blog/all_blogs.html',{'blogs':blogs})

def detail(request , blog_id):
    blog=get_object_or_404(Blog,pk=blog_id)
    return render(request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Site Metas -->
    <title>Yash Darji</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'portfolio/Teal and Orange Boxes Art & Design Logo.png' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'portfolio/Teal and Orange Boxes Art & Design Logo.png' %}">
        <!-- All core CSS -->
    <link href="{% static 'portfolio/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'portfolio/css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'portfolio/css/all.css' %}" rel="stylesheet">
    <link href="{% static 'portfolio/style.css' %}" rel="stylesheet">
    <link href="{% static 'portfolio/css/colors.css' %}" rel="stylesheet">

    <link href="{% static 'portfolio/css/responsive.css' %}" rel="stylesheet">



</head>
<body>
<!--{% load static %}
<h1>Blogs from Yash Darji</h1>

<h2>Yash has written {{ blogs.count }} blogs </h2>
{% for blog in blogs %}

<a href="{% url 'blog:detail' blog.id %}">

   <h2>{{ blog.title }}</h2></a>

   <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
   <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
{% endfor %}-->



{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Yash has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}
</body>

blog/templates/blog/detail.html
{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}